#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Command\Upload;
use App\Command\DownloadAssets;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new DownloadAssets());
$application->add(new Upload());

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$application->run();


